version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
    - "./frontend:/srv/app"
    ports:
    - "${FRONTEND_PORT}:3000"
  backend:
    build: ./backend
    volumes:
    - "./backend:/srv/app"


